import type { NextPage } from 'next';
import Head from 'next/head';
import { Header, Footer } from '../app';
import TitleSection from '../sections/title-section';
import { Container } from '@chakra-ui/react';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main>
        <Container maxW="xxl" minH="calc(90vh)" px={0}>
          <TitleSection />
        </Container>
      </main>
    </div>
  );
};

export default Home;
