import type { NextPage } from "next";
import Head from "next/head";
import { Header, Footer } from "../app";
import Heading from "../sections/heading";
import { Container } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main height="calc(90vh)">
        <Container maxW={["none", "750px", "970px", "1100px", "1440px"]} px={0}>
          <Heading />
        </Container>
      </main>
    </div>
  );
};

export default Home;
