import { ChakraProvider } from "@chakra-ui/react";
import { extendTheme } from "@chakra-ui/react";
import TitleSection from "../components/sections/title-section";
import { Header } from "./Header";
import { Footer } from "./Footer";
import Head from "next/head";

const colors = {
  purple: "#6334B1",
  green: "#28FF98",
  lightGreen: "#E7FFF1",
  lightBlue: "#CECFEA",
};
const styles = {
  global: {
    ul: {
      listStyleType: "none",
    },
    // styles for the `a`
    a: {
      _hover: {
        textDecoration: "none",
      },
    },
  },
};

const components = {};

const theme = extendTheme({
  colors,
  styles,
  components,
});
import { ReactNode } from "react";

const Layout = ({ children }: { children: ReactNode }): JSX.Element => {
  return (
    <ChakraProvider resetCSS theme={theme}>
      <Head>
        <title>Goby Network App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main>
        <TitleSection />
        {children}
      </main>
      <footer>
        <Footer />
      </footer>
    </ChakraProvider>
  );
};

export default Layout;
